---
- name: Import variables file
  include_vars:
    file: role_vars.yml

- name: Create C:\temp
  win_file:
    path: C:\temp
    state: directory

- name: Copy PowerShell script to remote host
  win_template:
    src: files/Install-Latest.ps1
    dest: C:\temp\Install-Latest.ps1

- name: Execute PowerShell script
  win_shell: |
    $apps = "{{ apps | join(',') }}"
    C:\temp\Install-Latest.ps1 -Repository "{{ repository }}" -Apps ($apps -split ',')
  register: output

- name: PowerShell script output
  debug:
    var: output.stdout_lines

- name: Remove PowerShell script from remote host
  win_file:
    path: C:\temp\Install-Latest.ps1
    state: absent
