---
- name: "Import variables from installer_data.yml"
  include_vars:
    file: apps_vars.yml

#- name: Print apps.name
#  debug:
#    msg: {{ apps.name }}

- name: "Print apps.name"
  debug:
    msg: "{{ apps }}"
